apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - args:
        - go
        - run
        - main.go
        env:
        - name: POSTGRES_URL
          value: postgres
        image: m1001/gobooks:1.0
        name: api
        ports:
        - containerPort: 8080
        resources: {}
        workingDir: /go/src/github.com/mblhaunted/gobooks
      restartPolicy: Always
status: {}
